Disable build on JDK 27-ea

diff --git a/.github/actions/run-gradle/action.yml b/.github/actions/run-gradle/action.yml
--- a/.github/actions/run-gradle/action.yml
+++ b/.github/actions/run-gradle/action.yml
@@ -5,6 +5,10 @@ inputs:
     required: true
     description: Gradle arguments
     default: build
+  broken-by-issue:
+    required: false
+    description: Expect the build to fail due the referenced issue
+    default: ""
   encryptionKey:
     required: true
     description: Gradle cache encryption key
@@ -33,3 +37,8 @@ runs:
         "-Dscan.value.GitHub job=${{ github.job }}" \
         javaToolchains \
         ${{ inputs.arguments }}
+        
+        if [ "$?" -eq 0 && ${{ inputs.broken-by-issue }} != "" ]; then
+          echo "Build was expected to fail, but it passed. Was ${{ inputs.broken-by-issue }} resolved?"
+          exit 1
+        fi
